# Generated by Django 3.0.5 on 2020-04-09 00:13

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(default='')),
                ('campaign_id', models.FloatField(default=-1)),
                ('auto_fb_post_mode', models.BooleanField(default=False)),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('goal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('donators', models.FloatField(default=0)),
                ('days_active', models.FloatField(default=0)),
                ('title', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('default_url', models.TextField(default='')),
                ('has_beneficiary', models.BooleanField(default=False)),
                ('turn_off_donations', models.BooleanField(default=False)),
                ('visible_in_search', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
                ('deactivated', models.BooleanField(default=False)),
                ('state', models.BooleanField(default=False)),
                ('campaign_image_url', models.URLField(default='')),
                ('launch_date', models.DateField(default='')),
                ('campaign_hearts', models.FloatField(default=0)),
                ('social_share_total', models.FloatField(default=0)),
                ('social_share_last_update', models.DateField(default='')),
                ('location_city', models.TextField(default='')),
                ('location_country', models.TextField(default='')),
                ('location_zip', models.TextField(default='')),
                ('is_charity', models.BooleanField(default=False)),
                ('charity_name', models.TextField(default='')),
                ('riskScore', models.FloatField(default=0)),
                ('riskScoreQuartile', models.FloatField(default=0)),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='api.Category')),
                ('currencycode', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='api.CurrencyCode')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('salt', models.TextField(default='0')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
