# Generated by Django 3.0.5 on 2020-04-07 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(default='')),
                ('campaign_id', models.IntegerField(default=-1)),
                ('auto_fb_post_mode', models.BooleanField(default=False)),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('goal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('donators', models.IntegerField(default=0)),
                ('days_active', models.IntegerField(default=0)),
                ('title', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('default_url', models.TextField(default='')),
                ('has_beneficiary', models.BooleanField(default=False)),
                ('turn_off_donations', models.BooleanField(default=False)),
                ('visible_in_search', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
                ('deactivated', models.BooleanField(default=False)),
                ('state', models.BooleanField(default=False)),
                ('campaign_image_url', models.URLField(default='')),
                ('launch_date', models.DateField(default='')),
                ('campaign_hearts', models.IntegerField(default=0)),
                ('social_share_total', models.IntegerField(default=0)),
                ('social_share_last_update', models.DateField(default='')),
                ('location_city', models.TextField(default='')),
                ('location_country', models.TextField(default='')),
                ('location_zip', models.IntegerField(default=0)),
                ('is_charity', models.BooleanField(default=False)),
                ('charity_name', models.TextField(default='')),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='api.Category')),
                ('currencycode', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='api.CurrencyCode')),
            ],
        ),
    ]
