# Generated by Django 3.0.5 on 2020-04-07 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
