# Generated by Django 3.0.5 on 2020-04-07 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_campaign_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='url',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='goal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
